// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_make_a_streak_of_solving_3_hard_puzzles = "CgkIldrbvbUdEAIQCQ"; // <GPGSID>
        public const string achievement_solve_an_expert_puzzle_without_any_undo = "CgkIldrbvbUdEAIQFQ"; // <GPGSID>
        public const string achievement_use_flip_colors = "CgkIldrbvbUdEAIQBQ"; // <GPGSID>
        public const string achievement_solve_an_expert_puzzle_in_less_than_1_minute = "CgkIldrbvbUdEAIQKA"; // <GPGSID>
        public const string achievement_solve_easy_puzzle_in_less_than_30_s = "CgkIldrbvbUdEAIQDw"; // <GPGSID>
        public const string achievement_make_a_streak_of_solving_10_giant_puzzles = "CgkIldrbvbUdEAIQIw"; // <GPGSID>
        public const string achievement_make_a_streak_of_solving_10_hard_puzzles = "CgkIldrbvbUdEAIQIQ"; // <GPGSID>
        public const string achievement_play_a_game_with_blackred_theme = "CgkIldrbvbUdEAIQDg"; // <GPGSID>
        public const string achievement_make_a_streak_of_solving_5_expert_puzzles = "CgkIldrbvbUdEAIQGg"; // <GPGSID>
        public const string achievement_solve_medium_puzzle_in_less_than_30_s = "CgkIldrbvbUdEAIQEA"; // <GPGSID>
        public const string achievement_use_infinity_moves = "CgkIldrbvbUdEAIQBw"; // <GPGSID>
        public const string achievement_solve_a_hard_puzzle_in_less_than_3_minutes = "CgkIldrbvbUdEAIQJA"; // <GPGSID>
        public const string achievement_solve_30_expert_puzzles = "CgkIldrbvbUdEAIQHw"; // <GPGSID>
        public const string achievement_solve_30_giant_puzzles = "CgkIldrbvbUdEAIQIA"; // <GPGSID>
        public const string achievement_solve_1_expert_puzzle = "CgkIldrbvbUdEAIQEg"; // <GPGSID>
        public const string achievement_solve_10_expert_puzzles = "CgkIldrbvbUdEAIQFw"; // <GPGSID>
        public const string achievement_play_a_game_with_redwhite_theme = "CgkIldrbvbUdEAIQDQ"; // <GPGSID>
        public const string achievement_solve_3_easy_puzzles = "CgkIldrbvbUdEAIQAQ"; // <GPGSID>
        public const string achievement_use_flip_vertical = "CgkIldrbvbUdEAIQBA"; // <GPGSID>
        public const string achievement_solve_the_giant_puzzle_in_less_than_1_minute = "CgkIldrbvbUdEAIQKQ"; // <GPGSID>
        public const string achievement_use_flip_horizontal = "CgkIldrbvbUdEAIQAw"; // <GPGSID>
        public const string achievement_solve_5_giant_puzzles = "CgkIldrbvbUdEAIQGA"; // <GPGSID>
        public const string achievement_make_a_streak_of_solving_10_expert_puzzles = "CgkIldrbvbUdEAIQIg"; // <GPGSID>
        public const string achievement_solve_an_expert_puzzle_in_less_than_3_minutes = "CgkIldrbvbUdEAIQJQ"; // <GPGSID>
        public const string achievement_solve_3_medium_puzzles = "CgkIldrbvbUdEAIQAg"; // <GPGSID>
        public const string achievement_make_a_streak_of_solving_3_expert_puzzles = "CgkIldrbvbUdEAIQCg"; // <GPGSID>
        public const string achievement_solve_10_hard_puzzles = "CgkIldrbvbUdEAIQFg"; // <GPGSID>
        public const string achievement_solve_30_medium_puzzles = "CgkIldrbvbUdEAIQHQ"; // <GPGSID>
        public const string achievement_solve_30_easy_puzzles = "CgkIldrbvbUdEAIQHA"; // <GPGSID>
        public const string achievement_use_infinity_timer = "CgkIldrbvbUdEAIQBg"; // <GPGSID>
        public const string achievement_solve_the_giant_puzzle_in_less_than_3_minutes = "CgkIldrbvbUdEAIQJg"; // <GPGSID>
        public const string achievement_solve_1_giant_puzzle = "CgkIldrbvbUdEAIQEw"; // <GPGSID>
        public const string achievement_solve_30_hard_puzzles = "CgkIldrbvbUdEAIQHg"; // <GPGSID>
        public const string achievement_make_a_streak_of_solving_5_hard_puzzles = "CgkIldrbvbUdEAIQGQ"; // <GPGSID>
        public const string achievement_solve_1_hard_puzzle = "CgkIldrbvbUdEAIQEQ"; // <GPGSID>
        public const string achievement_solve_a_hard_puzzle_without_any_undo = "CgkIldrbvbUdEAIQFA"; // <GPGSID>
        public const string achievement_use_exploder = "CgkIldrbvbUdEAIQCA"; // <GPGSID>
        public const string achievement_solve_a_hard_puzzle_in_less_than_1_minute = "CgkIldrbvbUdEAIQJw"; // <GPGSID>
        public const string achievement_play_a_game_with_circle_tiles = "CgkIldrbvbUdEAIQCw"; // <GPGSID>
        public const string achievement_make_a_streak_of_solving_5_giant_puzzles = "CgkIldrbvbUdEAIQGw"; // <GPGSID>
        public const string achievement_play_a_game_with_sharp_corner_square_tiles = "CgkIldrbvbUdEAIQDA"; // <GPGSID>

}

